//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLineStore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRequest
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UserID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
    }
}
